import { createStore } from 'vuex'
import Skill from "@/utils/Skill.js";
export default createStore({
  state: {
    lang: "zh_hans",
    meldingCate: 1,
    enableLv4Deco: false,
    skills: [
      // skills[0] = MHRise
      // skills[1] = MHRise:SB
      [
        new Skill(1, "A", 3, 2),
        new Skill(2, "A", 3, 2),
        new Skill(3, "A", 2, 2),
        new Skill(4, "A", 3, 2),
        new Skill(5, "A", 2, 2),
        new Skill(6, "A", 3, 2),
        new Skill(7, "S", 2, 1),
        new Skill(8, "A", 2, 2),
        new Skill(9, "A", 3, 2),
        new Skill(10, "A", 2, 2),
        new Skill(11, "A", 2, 2),
        new Skill(12, "S", 2, 1),
        new Skill(13, "B", 3, 2),
        new Skill(14, "B", 3, 2),
        new Skill(15, "B", 3, 2),
        new Skill(16, "B", 3, 2),
        new Skill(17, "B", 3, 2),
        new Skill(18, "B", 3, 2),
        new Skill(19, "A", 2, 2),
        new Skill(20, "A", 2, 2),
        new Skill(21, "A", 2, 2),
        new Skill(22, "S", 2, 1),
        new Skill(23, "A", 2, 2),
        new Skill(24, "A", 2, 2),
        new Skill(25, "A", 2, 2),
        new Skill(26, "S", 2, 1),
        new Skill(27, "A", 2, 2),
        new Skill(28, "B", 3, 2),
        new Skill(30, "S", 2, 1),
        new Skill(31, "A", 2, 2),
        new Skill(32, "S", 2, 1),
        new Skill(33, "C", 3, 3),
        new Skill(34, "A", 2, 2),
        new Skill(35, "A", 3, 2),
        new Skill(36, "A", 2, 1),
        new Skill(37, "S", 2, 1),
        new Skill(38, "S", 2, 1),
        new Skill(39, "B", 3, 2),
        new Skill(40, "B", 3, 2),
        new Skill(41, "B", 3, 2),
        new Skill(42, "C", 3, 3),
        new Skill(43, "C", 1, 1),
        new Skill(44, "C", 1, 1),
        new Skill(45, "S", 2, 1),
        new Skill(46, "A", 2, 1),
        new Skill(47, "A", 2, 1),
        new Skill(48, "A", 2, 2),
        new Skill(49, "S", 2, 1),
        new Skill(50, "S", 2, 1),
        new Skill(51, "S", 2, 1),
        new Skill(52, "B", 3, 2),
        new Skill(53, "B", 3, 2),
        new Skill(54, "B", 2, 2),
        new Skill(55, "S", 2, 1),
        new Skill(56, "B", 3, 3),
        new Skill(57, "B", 3, 2),
        new Skill(58, "C", 3, 3),
        new Skill(59, "C", 3, 3),
        new Skill(60, "B", 3, 2),
        new Skill(61, "B", 3, 2),
        new Skill(62, "B", 3, 2),
        new Skill(63, "B", 3, 2),
        new Skill(64, "B", 3, 2),
        new Skill(65, "B", 3, 2),
        new Skill(66, "B", 3, 2),
        new Skill(67, "C", 3, 3),
        new Skill(68, "C", 3, 3),
        new Skill(69, "C", 3, 3),
        new Skill(70, "C", 3, 3),
        new Skill(71, "C", 3, 3),
        new Skill(72, "B", 3, 2),
        new Skill(73, "C", 3, 3),
        new Skill(74, "C", 3, 3),
        new Skill(75, "C", 3, 3),
        new Skill(76, "B", 3, 2),
        new Skill(77, "C", 2, 2),
        new Skill(78, "C", 3, 3),
        new Skill(79, "C", 4, 4),
        new Skill(80, "C", 3, 3),
        new Skill(81, "B", 3, 2),
        new Skill(84, "S", 2, 1),
        new Skill(85, "B", 3, 2),
        new Skill(86, "C", 3, 3),
        new Skill(87, "S", 2, 1),
        new Skill(88, "C", 3, 3),
        new Skill(89, "B", 3, 2),
        new Skill(90, "C", 3, 3),
        new Skill(91, "A", 3, 2),
        new Skill(92, "C", 1, 1),
        new Skill(93, "B", 3, 2),
        new Skill(94, "S", 1, 1),
        new Skill(95, "C", 1, 1),
        new Skill(96, "C", 3, 3),
        new Skill(97, "C", 1, 1),
        new Skill(98, "C", 1, 1),
        new Skill(99, "C", 1, 1),
        new Skill(104, "C", 3, 3),
        new Skill(105, "C", 3, 3),
        new Skill(106, "B", 3, 2),
        new Skill(107, "B", 3, 2),
        new Skill(108, "A", 2, 2)
      ], 
      [
        new Skill(1, "A", 3, 2),
        new Skill(2, "A", 3, 2),
        new Skill(3, "A", 2, 2),
        new Skill(4, "A", 3, 2),
        new Skill(5, "A", 2, 2),
        new Skill(6, "A", 3, 2),
        new Skill(7, "S", 2, 1),
        new Skill(8, "A", 2, 2),
        new Skill(9, "A", 3, 2),
        new Skill(10, "A", 2, 2),
        new Skill(11, "A", 2, 2),
        new Skill(12, "S", 2, 1),
        new Skill(13, "B", 3, 2), // not obtainable from new melding as the first skill
        new Skill(14, "B", 3, 2), // not obtainable from new melding as the first skill
        new Skill(15, "B", 3, 2), // not obtainable from new melding as the first skill
        new Skill(16, "B", 3, 2), // not obtainable from new melding as the first skill
        new Skill(17, "B", 3, 2), // not obtainable from new melding as the first skill
        new Skill(18, "B", 3, 2), // not obtainable from new melding as the first skill
        new Skill(19, "A", 2, 2),
        new Skill(20, "A", 2, 2),
        new Skill(21, "A", 2, 2),
        new Skill(22, "S", 2, 1),
        new Skill(23, "A", 2, 2),
        new Skill(24, "A", 2, 2),
        new Skill(25, "A", 2, 2),
        new Skill(26, "S", 2, 1),
        new Skill(27, "A", 2, 2),
        new Skill(28, "B", 3, 2), // not obtainable from new melding
        new Skill(30, "S", 2, 1),
        new Skill(31, "A", 2, 2),
        new Skill(32, "S", 2, 1),
        new Skill(33, "C", 3, 3),
        new Skill(34, "A", 2, 2),
        new Skill(35, "A", 3, 2),
        new Skill(36, "A", 2, 1),
        new Skill(37, "S", 2, 1),
        new Skill(38, "S", 2, 1),
        new Skill(39, "B", 3, 2),
        new Skill(40, "B", 3, 2),
        new Skill(41, "B", 3, 2),
        new Skill(42, "C", 3, 3),
        new Skill(43, "C", 1, 1),
        new Skill(44, "C", 1, 1),
        new Skill(45, "S", 2, 1),
        new Skill(46, "A", 2, 1),
        new Skill(47, "A", 2, 1),
        new Skill(48, "A", 2, 2),
        new Skill(49, "S", 2, 1),
        new Skill(50, "S", 2, 1),
        new Skill(51, "S", 2, 1),
        new Skill(52, "B", 3, 2),
        new Skill(53, "B", 3, 2),
        new Skill(54, "B", 3, 2), // lv2 -> lv3 for first skill
        new Skill(55, "S", 2, 1),
        new Skill(56, "B", 3, 3),
        new Skill(57, "B", 3, 2),
        new Skill(58, "C", 3, 3),
        new Skill(59, "C", 3, 3),
        new Skill(60, "B", 3, 2),
        new Skill(61, "B", 3, 2),
        new Skill(62, "B", 3, 2),
        new Skill(63, "B", 3, 2),
        new Skill(64, "B", 3, 2),
        new Skill(65, "B", 3, 2),
        new Skill(66, "B", 3, 2),
        new Skill(67, "C", 3, 3), // not obtainable from new melding
        new Skill(68, "C", 3, 3), // not obtainable from new melding
        new Skill(69, "C", 3, 3), // not obtainable from new melding
        new Skill(70, "C", 3, 3), // not obtainable from new melding
        new Skill(71, "C", 3, 3), // not obtainable from new melding
        new Skill(72, "B", 3, 2), // not obtainable from new melding as the first skill
        new Skill(73, "C", 3, 3), // not obtainable from new melding
        new Skill(74, "C", 3, 3), // not obtainable from new melding
        new Skill(75, "C", 3, 3), // not obtainable from new melding
        new Skill(76, "B", 3, 2),
        new Skill(77, "C", 2, 2), // not obtainable from new melding
        new Skill(78, "C", 3, 3), // not obtainable from new melding
        new Skill(79, "C", 4, 4), // not obtainable from new melding
        new Skill(80, "C", 3, 3), // not obtainable from new melding
        new Skill(81, "B", 3, 2),
        new Skill(84, "S", 2, 1),
        new Skill(85, "B", 3, 2),
        new Skill(86, "C", 3, 3), // not obtainable from new melding
        new Skill(87, "S", 2, 1),
        new Skill(88, "C", 3, 3),
        new Skill(89, "B", 3, 2),
        new Skill(90, "C", 3, 3),
        new Skill(91, "A", 3, 2),
        new Skill(92, "C", 1, 1),
        new Skill(93, "B", 3, 2),
        new Skill(94, "S", 1, 1), // not obtainable from new melding
        new Skill(95, "C", 1, 1),
        new Skill(96, "C", 3, 3),
        new Skill(97, "C", 1, 1), // not obtainable from new melding
        new Skill(98, "C", 1, 1), // not obtainable from new melding
        new Skill(99, "C", 1, 1),
        new Skill(104, "C", 3, 3),
        new Skill(105, "C", 3, 3),
        new Skill(106, "B", 3, 2),
        new Skill(107, "B", 3, 2),
        new Skill(108, "A", 2, 2),
        // MHRise SB Skills
        new Skill(116, "A", 2, 2),
        new Skill(122, "B", 2, 1),
        new Skill(123, "C", 1, 1),
        new Skill(124, "A", 2, 2),
        new Skill(125, "A", 2, 2),
        new Skill(126, "A", 2, 1),
        new Skill(127, "A", 2, 2),
        new Skill(128, "A", 2, 2),
        new Skill(129, "C", 1, 1),
        new Skill(131, "A", 2, 2),
      ]
    ],
  },
  mutations: {
  },
  actions: {
  },
  modules: {
  }
})
